### ISSUE TITLE
[Feature Request] Add and delete runners in bulk

### ISSUE THREAD

**Issue by SpriteOvO** [vbem/multi-runners#19]
It would be convenient if we could add/delete runners with just one command.

For example, add 10 runners at once

```bash
./mr.bash add --org <ORG> --repo <REPO> --count 10
```

delete 5 runners **by organization/repo** at once

```bash
./mr.bash del --org <ORG> --repo <REPO> --count 5
```

delete all runners **by organization/repo** at once

```bash
./mr.bash del --org <ORG> --repo <REPO> --all
```

Thanks for your great work on this tool!

**Comment by vbem** [comment]
Thanks for your fantastic suggestion, I'll keep this issue open and try to add this feature in coming weeks.

**Comment by vbem** [comment]
Hi @SpriteOvO 

Your suggestion has been implemented, please refer to the latest `README`.

**Comment by SpriteOvO** [comment]
Excited! Thanks for your work~ :D
