### ISSUE TITLE
Multiple runners on the same machine fail

### ISSUE THREAD

**Issue by danieltamas** [vbem/multi-runners#2]
Hello. The problem is this:
- installed 6 runners on the same machine
- all 6 got connected and ready for jobs
- when the workflow started, they all failed
- error: package.json not found

From the looks of it, only one managed to download the repo it was supposed
to build on, the rest failed and continue to fail. 

It seems the repo gets deleted for some reason from the `/_work/` folder
What may cause this and what is the fix?

Thank you

**Comment by vbem** [comment]
Hi,

The `_work` subfolder is maintained by GitHub self-hosted runner app it self, which ["Don't need to have a clean instance for every job execution"](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners). Did you checkout your code every time in your workflow file, such as:

```yaml
    steps:
      - uses: actions/checkout@v4
```

**Comment by danieltamas** [comment]
Hey. The problem was with the subflows. 
If anyone is interested, the flows must be complete in order for each runner to 
know what they are doing. 

There are 2 options for this:
1. to speed up things with caching, use artifacts
2. write the entire flow so when fresh runner picks up a new job, it has all the info
