### ISSUE TITLE
"Must have admin rights to repository" - Thrown by API

### ISSUE THREAD

**Issue by mikeslinkman** [vbem/multi-runners#5]
Thank you for doing the work and providing a solution to use multiple runners on a single host. However I'm running into an issue when trying to run the `pat2token` /  `add` commands to setup my runners. Based on the error I'm pretty certain that the issue is on my side but I can't figure it out.

I created a PAT in my profile (classic) with the following permission and added it to the `.env` file. I also tried the recommend approach for creating a fine grained token but could not find the mentioned 'organization_self_hosted_runners' permission. Any guidance would be appreciated. 

Good to mention is that I'm the owner of the organisation and when trying it for a specific repository it appears to work like expected

<img width="622" alt="Screenshot 2024-03-09 at 16 32 40" src="https://github.com/vbem/multi-runners/assets/3715598/1240c06a-ed33-404c-8b78-f5ce4c5e28f9">

**Comment by vbem** [comment]
Hi @mikeslinkman,

Thank you so much for the valuable inputs.

I've update the `README.txt` according to GitHub latest official API documents:

PAT types | Repository level runners | Organization level runners
--- | --- | ---
*Fine-grained PAT* (recommended) | Referring to [repo API](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-a-repository), the `administration:write` permission is required. | Referring to [org policy](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization) & [org API](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization), the `organization_self_hosted_runners:write` permission is required.
*Classic PAT* | Referring to [repo API](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-a-repository), need the `repo` scope | Refer to [repo API](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization), need the `admin:org` scope; if the repository is private, `repo` scope is also required.

Simply speaking, for organization level registration, the *classic PAT* requires `admin:org` scope now, and *Fine-grained PAT* requires `organization_self_hosted_runners:write` permission on specified organization. Note that, it may need to at first enable the "Organization Policy" for an organization before use *Fine-grained PAT* on such organization.

![image](https://github.com/vbem/multi-runners/assets/5989600/2f7117a3-193d-4772-aa96-fde9c9e09e78)

![image](https://github.com/vbem/multi-runners/assets/5989600/3f1463f3-e23d-4050-b4c1-75eaae46251f)

![image](https://github.com/vbem/multi-runners/assets/5989600/d02bcfba-7b83-46c5-b709-26a9a64a8311)

![image](https://github.com/vbem/multi-runners/assets/5989600/46fa1357-4172-49d2-b657-033a4ff72c6f)

**Comment by mikeslinkman** [comment]
@vbem Perfect worked like a charm, also missed the resource owner bit so that probably didn't help as well
