### ISSUE TITLE
Runners running out of space

### ISSUE THREAD

**Issue by vdurante** [vbem/multi-runners#7]
Hey, awesome tool! Love it so far!

I was wondering if there is a guideline on how to cleanup leftover files of the runners? Can I delete the _work directories? They are by far the heaviest ones.

Thanks!

**Comment by vbem** [comment]
Hi @vdurante,

Thank you for trying this small wrapper.

Though GitHub does not provide much documentation to describe the directory structure of the self-hosted runner, most users may noticed that the `_work/` sub-directory under runner installing path is the parent folder of "workspace" directories (i.e. `${{ runner.workspace }}`). Users can clean it on demand to save disk.

Meanwhile, it seems GitHub self-hosted runners also created other sub-directories to store expired Runner executable (e.g. `bin.*/`, ` externals.*/`, etc.), runner logs (e.g. `_diag/`). These can also be  released.

My suggestion is, on your host, manually or automatically, you can `del` all old runners and re-`add` them back, which brings these runners completely clean.
