### ISSUE TITLE
SELinux fail because of binary location

### ISSUE THREAD

**Issue by tonybolzan** [vbem/multi-runners#9]
On RHEL9 SELinux fail because of binary location 
Runnig `chcon -t bin_t /home/runner-0/runner/runsvc.sh` resolve the problem

- Include the `chcon` to `add` comand

```diff
@@ -253,7 +253,7 @@
 		cd .. && tar -xzf "$tarpath"
 		echo "$dotenv" >> .env
 		./config.sh --unattended --replace --url '$url' --token '$token' --name '$name' --labels '$labels' --runnergroup '$group'
-		sudo ./svc.sh install '$user' && sudo ./svc.sh start
+		sudo ./svc.sh install '$user' && chcon -t bin_t ./runsvc.sh && sudo ./svc.sh start
 	__
 }

```

Error Log
```log
May 07 18:39:26 github-runner-ci systemd[1644]: actions.runner.org.runner-0@github-runner-ci.service: Failed at step EXEC spawning /home/runner-0/runner/runsvc.sh: Permission denied
May 07 18:39:26 github-runner-ci systemd[1]: actions.runner.org.runner-0@github-runner-ci.service: Main process exited, code=exited, status=203/EXE
```

**Comment by vbem** [comment]
Thank you very much for your input @tonybolzan . 👍

I don't have the selinux environment. But found a SElinux built-in `selinuxenabled` CLI checker through Google-fu and then updated main branch with following code:

```bash
        sudo ./svc.sh install '$user'
        if selinuxenabled &>/dev/null; then # https://github.com/vbem/multi-runners/issues/9
            chcon -t bin_t ./runsvc.sh
        fi
        sudo ./svc.sh start
```

Please feel free to let me know if this works for SELinux.

**Comment by tonybolzan** [comment]
This `if` can be fail in debian/ubuntu because this command don't exists.
Maybe replicate the test from GitHub original code
```bash
    command -v getenforce > /dev/null
    if [ $? -eq 0 ]; then
        selinuxEnabled=$(getenforce)
        if [[ $selinuxEnabled == "Enforcing" ]]; then
            chcon -t bin_t ./runsvc.sh
        fi
    fi
```
https://github.com/actions/runner/blob/54052b94fb525a8bf30cc672c1ab103ac65297db/src/Misc/layoutbin/systemd.svc.sh.template#L79

**Comment by vbem** [comment]
> This `if` can be fail in debian/ubuntu because this command don't exists. Maybe replicate the test from GitHub original code
> 
> ```shell
>     command -v getenforce > /dev/null
>     if [ $? -eq 0 ]; then
>         selinuxEnabled=$(getenforce)
>         if [[ $selinuxEnabled == "Enforcing" ]]; then
>             chcon -t bin_t ./runsvc.sh
>         fi
>     fi
> ```
> 
> https://github.com/actions/runner/blob/54052b94fb525a8bf30cc672c1ab103ac65297db/src/Misc/layoutbin/systemd.svc.sh.template#L79

This is really a more compatible solution! I've update the code. Thanks.
